# Generated by Django 4.1.7 on 2023-03-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_exel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='price',
            new_name='my_price',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='name',
            new_name='title',
        ),
    ]
