# Generated by Django 4.1.7 on 2023-03-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_exel', '0004_mymodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='image',
        ),
    ]
