# Generated by Django 4.1.7 on 2023-03-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_exel', '0005_remove_mymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='image',
            field=models.FileField(null=True, upload_to='img'),
        ),
    ]
